# Numpy

In [1]:
import numpy as np

In [2]:
# Creating a numpy array from a list
arr = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 0]]
np_arr = np.array(arr)
np_arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]])

In [3]:
type(np_arr)

numpy.ndarray

In [4]:
# Creating an array of zeros
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
# Creating an array of ones
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# Generating an array of any value
np.full((4, 3), 4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [11]:
# Identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
# Array of random integers
np.random.randint(1, 100, (3, 5))

array([[72, 83, 24, 56, 28],
       [59, 94, 15, 87, 75],
       [95,  1, 22, 95, 50]])

In [13]:
np.random.randint(1, 10, 5)

array([5, 2, 9, 3, 5])

In [14]:
np.linspace(1, 2)
# Gives 50 equal intervals between 1 and 2

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [19]:
np.linspace(0, 11, 100)
# Gives 100 equal intervals between 0 and 11

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ,
        1.11111111,  1.22222222,  1.33333333,  1.44444444,  1.55555556,
        1.66666667,  1.77777778,  1.88888889,  2.        ,  2.11111111,
        2.22222222,  2.33333333,  2.44444444,  2.55555556,  2.66666667,
        2.77777778,  2.88888889,  3.        ,  3.11111111,  3.22222222,
        3.33333333,  3.44444444,  3.55555556,  3.66666667,  3.77777778,
        3.88888889,  4.        ,  4.11111111,  4.22222222,  4.33333333,
        4.44444444,  4.55555556,  4.66666667,  4.77777778,  4.88888889,
        5.        ,  5.11111111,  5.22222222,  5.33333333,  5.44444444,
        5.55555556,  5.66666667,  5.77777778,  5.88888889,  6.        ,
        6.11111111,  6.22222222,  6.33333333,  6.44444444,  6.55555556,
        6.66666667,  6.77777778,  6.88888889,  7.        ,  7.11111111,
        7.22222222,  7.33333333,  7.44444444,  7.55555556,  7.66

### Properties of a Numpy Array

In [20]:
# Size of array
np_arr.size

10

In [21]:
# Dimension of array ie axis present in the array
np_arr.ndim

2

In [22]:
# Shape of array
np_arr.shape

(5, 2)

### Operations with Numpy Array

In [24]:
# Addion operation
np_arr + 100

# Subtraction, multiplication, division, and other common operations can be performed on the array

array([[101, 102],
       [103, 104],
       [105, 106],
       [107, 108],
       [109, 100]])

In [25]:
# Minimum
np_arr.min()

0

In [26]:
# Maximum
np_arr.max()

9

In [28]:
# Standard deviation
np_arr.std()

2.8722813232690143

In [31]:
# Variance
np_arr.var()

8.25

In [33]:
# sine value
np.sin(np_arr)

# Same can be done for cos, log and tan

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825],
       [ 0.41211849,  0.        ]])

In [34]:
np.pi

3.141592653589793

### Accessing Elements of an Array

In [40]:
# Reshaping an array
new_arr = np.random.randint(1, 25, (20,)).reshape(4, 5)
new_arr

array([[16, 19, 18, 10, 20],
       [ 6, 21,  8, 16, 20],
       [ 5, 17,  2,  7,  6],
       [18, 21,  6,  4, 20]])

In [49]:
new_arr[0:, 0]

array([16,  6,  5, 18])

In [48]:
new_arr[0:, 0:2]

array([[16, 19],
       [ 6, 21],
       [ 5, 17],
       [18, 21]])