# 00. Pytouch Fundamental

## Importing PyTorch
Let's start by importing PyTorch and checking the version we're using.

In [1]:
import torch
torch.__version__

'2.2.1+cu121'

## Introduction to Tensors
Tensors are the fundamental building block of machine learning.

### Creating Tensors

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
scalar.shape

torch.Size([])

In [6]:
# vector
vector = torch.tensor([7,8])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])

In [10]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
# Tensor
TENSOR = torch.tensor([[[1,2,3,4],
                        [3,6,9,10],
                        [2,4,5,7]]])

In [18]:
TENSOR

tensor([[[ 1,  2,  3,  4],
         [ 3,  6,  9, 10],
         [ 2,  4,  5,  7]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 4])

## Random tensors

In [21]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
print(random_tensor)
print(f"Datatype of tensor: {random_tensor.dtype}")
print(f"Shape of tensor: {random_tensor.shape}")

tensor([[4.8799e-01, 5.2784e-01, 1.2342e-01, 6.0945e-01],
        [7.6239e-01, 8.2446e-01, 2.5098e-01, 2.1070e-01],
        [3.0285e-04, 9.0900e-01, 1.2868e-01, 5.0403e-01]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])


In [22]:
# Create a random tensor of size (1, 3, 4)
random_tensor = torch.rand(size=(1, 3, 4))
print(random_tensor)
print(f"Datatype of tensor: {random_tensor.dtype}")
print(f"Shape of tensor: {random_tensor.shape}")

tensor([[[0.9089, 0.1796, 0.7647, 0.5707],
         [0.7986, 0.4975, 0.9378, 0.2205],
         [0.6439, 0.7810, 0.9962, 0.2031]]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([1, 3, 4])


## Zeros and ones

In [23]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
print(zeros)
print(f"Datatype of tensor: {zeros.dtype}")

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Datatype of tensor: torch.float32


In [24]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
print(ones)
print(f"Datatype of tensor: {ones.dtype}")

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Datatype of tensor: torch.float32


# Creating a range and tensors like

In [26]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
print(zero_to_ten)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [27]:
# tensors like
ten_zeros = torch.zeros_like(input=zero_to_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [31]:
ten_ones = torch.ones_like(input=zero_to_ten)
print(ten_ones)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


# Tensor datatypes

In [28]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

print(float_32_tensor)
print(f"Dimension of tensor: {float_32_tensor.ndim}")
print(f"Shape of tensor: {float_32_tensor.shape}")
print(f"Datatype of tensor: {float_32_tensor.dtype}")
print(f"Device tensor is stored on:  {float_32_tensor.device}")

tensor([3., 6., 9.])
Dimension of tensor: 1
Shape of tensor: torch.Size([3])
Datatype of tensor: torch.float32
Device tensor is stored on:  cpu


## Manipulating tensors (tensor operations)

In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

These operations are often a wonderful dance between:

- Addition
- Substraction
- Multiplication (element-wise)
- Division
- Matrix multiplication (dot product)

In [32]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
print("Before Operation")
print(tensor)
print("\nAfter Operation")
print(tensor + 10)

Before Operation
tensor([1, 2, 3])

After Operation
tensor([11, 12, 13])


In [33]:
tensor = torch.tensor([1, 2, 3])
print("Before Operation")
print(tensor)
print("\nAfter Operation")
print(tensor - 10)

Before Operation
tensor([1, 2, 3])

After Operation
tensor([-9, -8, -7])


In [34]:
# Can also use torch functions
torch.add(tensor, 5)

tensor([6, 7, 8])

In [35]:
torch.subtract(tensor, 2)

tensor([-1,  0,  1])

In [36]:
# Element-wise matrix multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [37]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

There are two main rules that performing matrix multiplication needs to satify:
1. The **inner dimensions** must match:
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of the **outer dimensions**
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)

## Transpose
One of the ways to do this is with a transpose (switch the dimensions of a given tensor).

In [38]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [39]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [40]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [41]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


Neural networks are full of matrix multiplications and dot products.

Finding the min, max, mean, sum, etc (aggregation)

In [42]:
# Create a tensor
x = torch.arange(0, 100, 10)
print(x)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [43]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


## Positional min/max

In [44]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


## Change tensor datatype

In [45]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [46]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

## Reshaping, stacking, squeezing and unsqueezing

* Rehsaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

### Reshaping

In [47]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
print(x)
print(x.shape)

tensor([1., 2., 3., 4., 5., 6., 7.])
torch.Size([7])


In [48]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
print(x_reshaped)
print(x_reshaped.shape)

tensor([[1., 2., 3., 4., 5., 6., 7.]])
torch.Size([1, 7])


In [49]:
# Change view (keeps same data as original but changes view)
z = x.view(1, 7)
print(z)
print(z.shape)

tensor([[1., 2., 3., 4., 5., 6., 7.]])
torch.Size([1, 7])


### Stacking

In [55]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

### Squeeze

In [56]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


And to do the reverse of `torch.squeeze()` you can use `torch.unsqueeze()` to add a dimension value of 1 at a specific index.

In [57]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


## Indexing (selecting data from tensors)

In [58]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [59]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [60]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [61]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [62]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [63]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

## PyTorch tensors & NumPy

Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

* `torch.from_numpy(ndarray)` - NumPy array -> PyTorch tensor.
* `torch.Tensor.numpy()` - PyTorch tensor -> NumPy array.

In [64]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
print(f"Numpy Array {array}")
print(f"Tensor {tensor}")

Numpy Array [1. 2. 3. 4. 5. 6. 7.]
Tensor tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
